### ISSUE TITLE
aps/apm Counting

### ISSUE THREAD

**Issue by jeangeorgesdestruel** [RemiSaurel/PoggersTyper#2]
The number of aps/apm are counted by the number of letter entered, and not by the **good** number of keystroke.

A possible fix could be verifying the key hit before adding it to the aps/apm counter

This is an example of how a player can abuse of this situation
![image](https://user-images.githubusercontent.com/62297436/140969493-e4c31f0e-f26c-4115-a130-e2829f5cc3ed.png)

**Comment by RemiSaurel** [comment]
👍
