### ISSUE TITLE
CTRL C CRTL V

### ISSUE THREAD

**Issue by Fricoue** [RemiSaurel/PoggersTyper#3]
SO we can put the number of letters between 14 and 16 and boom we only have "particulièrement" and we ctrl c ctrl v and we break the score. This kind of behavior should be fixed because it allows people to set really high scores on the leaderboard by doing nothing fix pls

![image](https://user-images.githubusercontent.com/62333955/141082232-1de5e7a5-044e-4e73-86d5-5cfb10abfd60.png)

**Comment by RemiSaurel** [comment]
👍
